# Generated by Django 3.2 on 2021-07-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20210713_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='date_of_birth',
            field=models.DateField(default='2000-06-18'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
