# Generated by Django 3.2 on 2021-07-18 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_register_account_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='account_created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
