# Generated by Django 3.2 on 2021-07-19 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='User_Image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.user_image'),
        ),
    ]
