# Generated by Django 3.2 on 2021-07-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_register_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_image',
            name='User_Image',
            field=models.ImageField(blank=True, null=True, upload_to='user images'),
        ),
    ]
