# Generated by Django 3.2 on 2021-07-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_user_image_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='User_Image',
            new_name='User_Photo',
        ),
        migrations.RenameField(
            model_name='user_image',
            old_name='User_Image',
            new_name='photo',
        ),
    ]
