# Generated by Django 3.2 on 2021-07-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_rename_user_photo_register_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_image',
            name='photo',
            field=models.ImageField(upload_to='user images'),
        ),
    ]
