# Generated by Django 3.2 on 2021-07-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_alter_user_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_image',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user images'),
        ),
    ]
