# Generated by Django 3.2 on 2021-07-29 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_alter_user_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='user_photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.user_image'),
        ),
    ]
