# Generated by Django 3.2 on 2021-07-31 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_articles_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.register'),
        ),
    ]
