# Generated by Django 3.2 on 2021-08-03 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_auto_20210801_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='body',
            new_name='contant',
        ),
    ]
