# Generated by Django 3.2 on 2021-08-03 08:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_rename_contant_articles_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='articles/cover_photo'),
        ),
    ]
