# Generated by Django 3.2 on 2021-08-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_auto_20210803_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='cover_photo',
            field=models.ImageField(upload_to='articles/cover_photo'),
        ),
    ]
