# Generated by Django 3.2 on 2021-08-03 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_alter_articles_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='blog_created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='articles',
            name='tag',
            field=models.CharField(default='HTML', max_length=50),
            preserve_default=False,
        ),
    ]
